export const Municipios = [
    // { "key": "1896", "label": "Aconchi" },
    // { "key": "1897", "label": "Agua Prieta" },
    { "key": "1898", "label": "Alamos", "sucursal":'Navojoa'  },
    // { "key": "1899", "label": "Altar" },
    // { "key": "1900", "label": "Arivechi" },
    // { "key": "1901", "label": "Arizpe" },
    // { "key": "1902", "label": "Atil" },
    // { "key": "1903", "label": "Bacadéhuachi" },
    // { "key": "1904", "label": "Bacanora" },
    // { "key": "1905", "label": "Bacerac" },
    // { "key": "1906", "label": "Bacoachi" },
    { "key": "1907", "label": "Bácum", "sucursal": 'Obregon' },
    // { "key": "1908", "label": "Banámichi" },
    // { "key": "1909", "label": "Baviácora" },
    // { "key": "1910", "label": "Bavispe" },
    // { "key": "1911", "label": "Benjamín Hill" },
    // { "key": "1912", "label": "Caborca" },
    { "key": "1913", "label": "Cajeme", "sucursal": 'Obregon' },
    // { "key": "1914", "label": "Cananea" },
    // { "key": "1915", "label": "Carbó" },
    // { "key": "1916", "label": "La Colorada" },
    // { "key": "1917", "label": "Cucurpe" },
    // { "key": "1918", "label": "Cumpas" },
    // { "key": "1919", "label": "Divisaderos" },
    { "key": "1920", "label": "Empalme", "sucursal":'Obregon'  },
    { "key": "1921", "label": "Etchojoa", "sucursal": 'Navojoa' },
    // { "key": "1922", "label": "Fronteras" },
    // { "key": "1923", "label": "Granados" },
    // { "key": "1924", "label": "Guaymas" },
    // { "key": "1925", "label": "Hermosillo" },
    // { "key": "1926", "label": "Huachinera" },
    // { "key": "1927", "label": "Huásabas" },
    { "key": "1928", "label": "Huatabampo", "sucursal":'Huatabampo'  },
    // { "key": "1929", "label": "Huépac" },
    // { "key": "1930", "label": "Imuris" },
    // { "key": "1931", "label": "Magdalena" },
    // { "key": "1932", "label": "Mazatán" },
    // { "key": "1933", "label": "Moctezuma" },
    // { "key": "1934", "label": "Naco" },
    // { "key": "1935", "label": "Nácori Chico" },
    // { "key": "1936", "label": "Nacozari de García" },
    { "key": "1937", "label": "Navojoa", "sucursal": 'Navojoa' },
    // { "key": "1938", "label": "Nogales" },
    // { "key": "1939", "label": "Onavas" },
    // { "key": "1940", "label": "Opodepe" },
    // { "key": "1941", "label": "Oquitoa" },
    // { "key": "1942", "label": "Pitiquito" },
    // { "key": "1943", "label": "Puerto Peñasco" },
    { "key": "1944", "label": "Quiriego", "sucursal": 'Navojoa' },
    // { "key": "1945", "label": "Rayón" },
    // { "key": "1946", "label": "Rosario" },
    // { "key": "1947", "label": "Sahuaripa" },
    // { "key": "1948", "label": "San Felipe de Jesús" },
    // { "key": "1949", "label": "San Javier" },
    // { "key": "1950", "label": "San Luis Río Colorado" },
    // { "key": "1951", "label": "San Miguel de Horcasitas" },
    // { "key": "1952", "label": "San Pedro de la Cueva" },
    // { "key": "1953", "label": "Santa Ana" },
    // { "key": "1954", "label": "Santa Cruz" },
    // { "key": "1955", "label": "Sáric" },
    // { "key": "1956", "label": "Soyopa" },
    // { "key": "1957", "label": "Suaqui Grande" },
    // { "key": "1958", "label": "Tepache" },
    // { "key": "1959", "label": "Trincheras" },
    // { "key": "1960", "label": "Tubutama" },
    // { "key": "1961", "label": "Ures" },
    // { "key": "1962", "label": "Villa Hkeyalgo" },
    // { "key": "1963", "label": "Villa Pesqueira" },
    // { "key": "1964", "label": "Yécora" },
    // { "key": "1965", "label": "General Plutarco Elías Calles" },
    { "key": "1966", "label": "Benito Juárez", "sucursal": 'Obregon' },
    { "key": "1967", "label": "San Ignacio Río Muerto", "sucursal": 'Obregon' }
]    